name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pandoc and texlive
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended texlive-fonts-extra

    - name: Install dependencies
      run: make

    - name: Upload PDF and HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume-files
        path: |
          resume.pdf
          cv.pdf
          resume.html
          cv.html
        retention-days: 5

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        name: resume-files
        path: artifacts
        
    - name: Create Tag
      id: create_tag
      run: |
        DATE=$(date +'%Y%m%d-%H%M%S')
        echo "tag=v$DATE" >> $GITHUB_OUTPUT
        git tag v$DATE
        git push origin v$DATE
        
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ steps.create_tag.outputs.tag }}
        files: |
          artifacts/resume.pdf
          artifacts/cv.pdf
          artifacts/resume.html
          artifacts/cv.html
        generate_release_notes: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
