name: Makefile CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install pandoc and texlive
      run: |
        sudo apt-get update
        sudo apt-get install -y pandoc texlive-latex-base texlive-latex-extra texlive-fonts-recommended texlive-latex-recommended texlive-fonts-extra

    - name: Install dependencies
      run: make

    - name: Upload PDF and HTML artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume-files
        path: |
          resume.pdf
          cv.pdf
          resume.html
          cv.html
        retention-days: 5
